# -*- coding: utf-8 -*-
"""nlp_webinar_projects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eS7YFmu3LVFHCueJtt16yYV6Oixvvsv
"""

# simple text summary in python 
# import gensin module and summmarize function
!pip install gensim
from gensim.summarization.summarizer import summarize
# paragraph
paragraph="nnatural. language pro.cessing is t.he ability .of a compute.r. program to .understand. okay uncle how do. you do in. this wo.rld on. the cliff. jumping to thee river"
summ_per = summarize(paragraph,ratio=0.7)
print("percent summary:")
print(summ_per)

summ_words = summarize(paragraph,word_count=30)
print("\n")
print("word count summary")
print(summ_words)

from gensim.summarization import keywords
paragraph = "nnatural. language pro.cessing is t.he ability .of a compute.r. program to .understand. okay uncle how do. you do in. this wo.rld on. the cliff. jumping to thee river"
keywords_txt = keywords(paragraph)
print(keywords_txt)

import spacy
nlp = spacy.load("en_core_web_sm")
s1  = nlp("the weather is rainy")
s2 = nlp("it ii going to rain outside")
print("the similarity is:",s1.similarity(s2))

from textblob import TextBlob
words = ["Machne","Learnin"]
corrected_words = []
for i in words:
    corrected_words.append(TextBlob(i))
print("wrong words :",words)
print("corrected words are :")
for  i in corrected_words:
     print(i.correct(),end=" ")