# -*- coding: utf-8 -*-
"""nlpwebinar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NkEMZo4DGUvBKM-sZvcYeMMZFJY7IkcF
"""

pip install nltk

import nltk

nltk.download("all")

from nltk.stem import PorterStemmer
stemmer =  PorterStemmer()
print(stemmer.stem('studies'))

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('studies'))

from nltk import WordNetLemmatizer

lemma = WordNetLemmatizer()
word_list = ["Study","Studying","Studies","Studied"]

for w in word_list:
    print(lemma.lemmatize(w,pos="v"))

from nltk import WordNetLemmatizer

lemma   = WordNetLemmatizer()
word_list = ["studies","leaves","decreases","plays"]

for w in word_list:
    print(lemma.lemmatize(w))

from nltk import WordNetLemmatizer

lemma = WordNetLemmatizer()
word_list = ["am","is","are","was","were"]

for w in word_list:
    print(lemma.lemmatize(w,pos="v"))

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('studying',pos="v"))
print(lemmatizer.lemmatize('studying',pos="n"))
print(lemmatizer.lemmatize('studying',pos="a"))
print(lemmatizer.lemmatize('studying',pos="r"))

