# -*- coding: utf-8 -*-
"""stop_words_nltk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R08iMtP38F4HZcbCGpmFoqoZafa0xAwk
"""

pip install nltk

import nltk
# nltk.download('stopwords')
# nltk.download('all')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words("english"))
text = "Hello Mr.Smith,how are you? This is GLA university. we are studying NATURAL LANGUAGE PROCESSING"
words = word_tokenize(text)
filtered_sentence = []
for w in words:
  if w not in stop_words:
    filtered_sentence.append(w)
print(filtered_sentence)    
# print(stop_words)

# STEMMING
# i was taking ride in a car
# i was riding  in a car
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
ps = PorterStemmer()
example_words = ['python','pythoner','pythoning','pythoned','pythonly']
for w in  example_words:
    print(ps.stem(w))

# LANCASTER STEMMER 
# SNOWBALL

from nltk.stem import SnowballStemmer
sst = SnowballStemmer("english")
wordstostem=["give","given","giving","gave"]
for words in wordstostem:
  print(words+":---->>"+sst.stem(words))

